# Generated by Django 5.1.1 on 2024-09-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='tipo_procedimento',
            field=models.CharField(choices=[('vacinacao', 'Vacinação'), ('castracao', 'Castração'), ('lab', 'Exames laboratoriais'), ('imagem', 'Exames de imagem'), ('tumor', 'Remoção de tumores'), ('limpeza', 'Limpeza dental'), ('cirurgia', 'Cirurgia')], default='1', max_length=100),
        ),
    ]
