# Generated by Django 5.1.5 on 2025-02-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dadosanimal_status_saude'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='estoque',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
