# Generated by Django 5.1.5 on 2025-02-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_dadosanimal_medicamentos_em_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosanimal',
            name='medicamentos_em_uso',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.medicamento'),
        ),
    ]
