# Generated by Django 5.1.5 on 2025-02-21 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_medicamento_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='estoque',
        ),
        migrations.CreateModel(
            name='EstoqueMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=10)),
                ('medicamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque_medicamento', to='accounts.medicamento')),
            ],
        ),
    ]
