# Generated by Django 5.1.5 on 2025-02-24 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_dadosanimal_medicamentos_em_uso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosanimal',
            name='medicamentos_em_uso',
        ),
    ]
