# Generated by Django 5.1.5 on 2025-02-24 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_dadosanimal_medicamentos_em_uso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='frequecia',
            new_name='frequencia',
        ),
    ]
