# Generated by Django 5.0.2 on 2025-04-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_frequecia_medicamento_frequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosanimal',
            name='castrado',
            field=models.CharField(choices=[('s', 'SIM'), ('n', 'NÃO')], default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='data_hora_administracao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Administração'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='via_administracao',
            field=models.CharField(default='VO', max_length=100, verbose_name='Via de Administração'),
        ),
    ]
